name: SFDX Test Run on Push

on: 
  pull_request:
    branches:
      - master
    types: [closed]

jobs:
  deploy:
  
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v2    
      - name: Login
        uses: sfdx-actions/setup-sfdx@v1
        with:
          sfdx-auth-url: ${{ secrets.SFDX_AUTH_URL }}
      - run: pwd
      - run: ls -lrt
      # - name: Set Default
      #   run: sfdx force:config:set defaultdevhubusername=richard@otc2-richard-sandbox.com
      - name: Deploy
        run: sfdx force:source:deploy -x manifest/package.xml