name: SFDX Deploy and Test on Merge

on:  
  pull_request:
    branches:
      - dev
      - qa
    types: [closed]
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref }}
    steps:
      - name: Show Branch
        run: echo Deploying and testing to ${{ github.ref }}
      - uses: actions/checkout@v2
      - name: Login
        uses: sfdx-actions/setup-sfdx@v1
        with:
          sfdx-auth-url: ${{ secrets.SFDX_AUTH_URL }}
      - name: Deploy
        run: sfdx force:source:deploy -x manifest/package.xml
      - name: Get PR labels
        id: pr-labels
        uses: joerick/pr-labels-action@v1.0.6
      - name: Run Tests
        run: |
            if [ -n "$GITHUB_PR_LABEL_TEST_NONE" ]; then
              echo "'test none' label found.  No tests being run"
            elif [ -n "$GITHUB_PR_LABEL_TEST_ALL" ]; then
              echo "'test all' label found.  Running all tests"
            elif [ -n "$GITHUB_PR_LABEL_TEST_LOCAL" ]; then
              echo "'test local' label found.  Running local tests"
            elif [ -n "$GITHUB_PR_LABEL_TEST_SPECIFIED" ]; then
              echo "'test specified' label found.  Running specified tests"              
            else
              echo "No Teting Label"
              echo "Default to test local"
            fi
