name: SFDX Test Run on Push

on: push 
  # pull_request:
  #   branches:
  #     - dev
  #     - qa
  #     - uat
  #   types: [closed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref }} 
    steps:
      - name: Which branch
        run: echo ${{ github.ref }}      
      - uses: actions/checkout@v2    
      - name: Login
        uses: sfdx-actions/setup-sfdx@v1
        with:
          sfdx-auth-url: ${{ secrets.SFDX_AUTH_URL }}
      # - name: Set Default
      #   run: sfdx force:config:set defaultdevhubusername=richard@otc2-richard-sandbox.com
      - name: Deploy
        run: sfdx force:source:deploy -x manifest/package.xml
      - name: Test
        run: sfdx force:apex:test:run --testlevel RunLocalTests
