name: Pull Request Checks
on:
  pull_request:
    branches:
      - dev
      - qa
      - demo2

    types: [opened, synchronize, edited]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: Which type
      run: echo ${{ github.event.pull_request.type }}    
