name: Pull Request Checks
on:
  pull_request:
    # branches:
    #   - dev
    #   - qa

    types: [opened, synchronize]

jobs:
  # tasks-complete:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: kentaro-m/task-completed-checker-action@v0.1.0
  #     with:
  #       repo-token: "${{ secrets.GITHUB_TOKEN }}"

  label-check:
    runs-on: ubuntu-latest
    steps:
    - uses: begedin/variable-regex-extractor-action@v0.2.1
      id: tests
      with:
        pattern: |
          #BEGIN_TESTS([\s\S]*)#END_TESTS
    - name: Check for named tests
      run: |
        echo "${{steps.tests.outputs.value}}"
        testslist="${{steps.tests.outputs.value}}"
        testslist=`echo $testslist | sed 's/ *$//g'`
        [ -z "$testslist" ] && echo "Empty" || echo "Not empty"

    # - uses: mshick/add-pr-comment@v1
    #   with:
    #     message: |
    #       **Hello**
    #       🌏
    #       !
    #     repo-token: ${{ secrets.GITHUB_TOKEN }}
    #     repo-token-user-login: 'github-actions[bot]' # The user.login for temporary GitHub tokens
    #     allow-repeats: false # This is the default
    
