name: Pull Request Checks
on:
  pull_request:
    branches:
      - master
      - development
    types: [opened, synchronize]

jobs:
  label-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2 
    - run: echo Implement This