name: Pull Request Checks
on:
  pull_request:
    # branches:
    #   - master
    #   - development
    types: [opened, synchronize]

jobs:
  label-check:
    runs-on: ubuntu-latest

    steps:
    - uses: begedin/variable-regex-extractor-action@v1.1
      id: tests
      with:
        pattern: |
          `myVar:([^\s]*)`    
    - name: output value
      run: echo ${{steps.tests.output}}
    # - uses: actions/checkout@v2 
    # - run: echo Implement This