name: Pull Request Checks
on:
  pull_request:
    # branches:
    #   - dev
    #   - qa

    types: [opened, synchronize]

jobs:
  # tasks-complete:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: kentaro-m/task-completed-checker-action@v0.1.0
  #     with:
  #       repo-token: "${{ secrets.GITHUB_TOKEN }}"

  label-check:
    runs-on: ubuntu-latest
    steps:
    - uses: begedin/variable-regex-extractor-action@v0.2.1
      id: tests
      with:
        pattern: |
          #BEGIN_TESTS([\s\S]*)#END_TESTS
    - name: Check for named tests
      id: tests-found
      run: |
        echo "${{steps.tests.outputs.value}}"
        tests_list="${{steps.tests.outputs.value}}"
        tests_list=`echo $tests_list | tr '\n' ' '`
        tests_list=`echo $tests_list | tr '\r' ' '`
        tests_list=`echo $tests_list | sed 's/ *$//g'`
        [ -z "$tests_list" ] && echo "::set-output name=tests-added::false" || echo "::set-output name=tests-added::true"
    - uses: mshick/add-pr-comment@v1
      if: steps.tests-found.outputs.tests-added == 'false'
      with:
        message: |
          Please add your tests
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        repo-token-user-login: 'github-actions[bot]'
        allow-repeats: true
    - uses: mshick/add-pr-comment@v1
      if: steps.tests-found.outputs.tests-added == 'true'
      with:
        message: |
          Thank you for adding your tests
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        repo-token-user-login: 'github-actions[bot]'
        allow-repeats: true
    
