name: Pull Request Checks
on:
  pull_request:
    # branches:
    #   - master
    #   - development
    types: [opened, synchronize]

jobs:
  label-check:
    runs-on: ubuntu-latest

    steps:
    - uses: begedin/variable-regex-extractor-action@v0.2.1
      id: tests
      with:
        pattern: |
          myVar:([^\s]*)    
    - name: Run tests
      run: |
        echo "::set-output name=mix-test::foo"
      id: run_tests
      env:
        MIX_ENV: test
        PGHOST: localhost
        PGUSER: postgres          
    - name: output value
      run: echo ${{steps.tests.outputs.value}}
    # - uses: actions/checkout@v2 
    # - run: echo Implement This