name: Pull Request Checks
on:
  pull_request:
    # branches:
    #   - master
    #   - development
    types: [opened, synchronize]

jobs:
  label-check:
    runs-on: ubuntu-latest

    steps:
    - uses: begedin/variable-regex-extractor-action@v0.2.1
      id: tests
      with:
        pattern: |
          `myVar:([^\s]*)`    
    - name: output value
      run: echo ${{join(steps.tests.outputs.*, '\n')}}
    # - uses: actions/checkout@v2 
    # - run: echo Implement This